### PR TITLE
Add Spirit Tree Race support

### PR DESCRIPTION
**Pull request by Tigrex-Dai**
add Spirit Tree Race in Tricoder and meta file.

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
you should probably fix the scripts you made first. Numerous users reporting errors.

**Comment by Tigrex-Dai** [comment]
> you should probably fix the scripts you made first. Numerous users reporting errors. I suspect you didnt test as well as you should, as they are saying energy doesnt regen, etc.

Yes I am trying to fix, but there exist errors including files of Spirit Guardian race and idk why. Am looking into the problem.

**Comment by Tigrex-Dai** [comment]
> you should probably fix the scripts you made first. Numerous users reporting errors. I suspect you didnt test as well as you should, as they are saying energy doesnt regen, etc.

I think I should cancel the day&night effect first, and put it back when the problem is solved

**Comment by Tigrex-Dai** [comment]
Emergency fix, cancel effects that will cause problems and will reactived when problems are fixed

**Pull request merged**
