### PR TITLE
Shields, Dyes, and Clothing Fabricator Changes

### PR DESCRIPTION
**Pull request by Tamamo89**
-Tungsten and Durasteel shields now at respective tiered anvils and all shields in the anvil are located in the armours tab.
-All the Special FU Dyes (such as Penumbrite) are at the clothing fabricator.
-Ingredients and Dyes now have their own separate tabs.

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
Looks good except for relocating the dyes to the clothfab. They should remain in the generic clothing station too. Or was this purely to reduce clutter?

**Comment by Tamamo89** [comment]
Okay, i can do that. My logic was.
Primary Dyes Tier 1
Enhanced and Secondary Dyes Tier 2
Special FU Dyes Tier 3
But if you want the special fu dyes on the Tier 1 as well that is fine with me. Let me know if that's what you want me to do.

**Comment by sayterdarkwynd** [comment]
Yea, im fine with *your* logic.

The issue is players. They want their dyes, and they want them *immediately*. So yea, keep them all at tier 1, or it'll be an endless tirade of whining for them to put back to tier 1 anyhow.

**Comment by Tamamo89** [comment]
something went wrong with the repository and i dont know how to fix it. going to just make a new one. give me a second. to test, commit, etc.

**Pull request closed without merging**
