### PR TITLE
Quest Changes

### PR DESCRIPTION
**Pull request by Tamamo89**
-Starbooze Quest now followup to the next quest.
-Black Glass quest deprecating arcsmelter quest now unlocked by blast furnance quest.

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
the booze quests are intentionally not following up, so that people use the Tricorder.

**Comment by Tamamo89** [comment]
do you want me to do the same with the bee quest then? they're in the same category.

**Comment by sayterdarkwynd** [comment]
i dont want *any* of them doing auto-followup. the bee ones are probably fine as-is though.

**Comment by Tamamo89** [comment]
@sayterdarkwynd 
so you want the bee ones to be left as is with auto-followup.
Kay. I'll revert the changes to the booze quest then. Then will this be okay to merge?

**Pull request closed without merging**
