### PR TITLE
backlog of changes

### PR DESCRIPTION
**Pull request by giantcavespider**
remove rare world breaking object from precursor underground
hopefully fix that annoying bug with flyers swimming
fix mistake with monster/npc fall damage
remove forced gravity from lush dungeons (will now use world gravity)
nerf cattle feed harder
make nailery edible to robots
don't have objects be both crushable and siftable
re-add direstone crushing
some minor fixes

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
don't have objects be both crushable and siftable
- absolutely not. This is intentional , and desired, to provide agency on what output a player might desire. I won't approve this change for the master branch.

re-add direstone crushing
- It was removed for a reason. I see no benefit in this existing, as they are nearly impossible to mine in the first place. I'd prefer not to encourage it.

some minor fixes
- ...and they are?

**Comment by giantcavespider** [comment]
the change with crushing/sifting was made before and I assumed it was accidentally reverted by a contributor. (the original reason for doing so was the precursor forge).
the mmupgrade change was just me realizing a previous decision was probably a bad idea.

**Comment by edwardspec** [comment]
> I assumed it was accidentally reverted by a contributor.

Yes. These 3 crushings were removed in #3404. Argenttip accidentally readded them in eb3f8ca72aa.

**Comment by Argenttip** [comment]
2024_11_24_23_55_22_feedback_frackinuniverse_Discord

Black slime was added as per this list.

**Comment by sayterdarkwynd** [comment]
You don't need to agree: that's where they go.

**Comment by sayterdarkwynd** [comment]
"remove forced gravity from lush dungeons (will now use world gravity)"

For this change, have you tested the effect it has on the starting dungeon rope/jump areas? we can't provide a change to gravity if it nullifies the need for rope or the jump tech.

**Comment by giantcavespider** [comment]
that's not for the dark cavern, it's for vina's lab and the overgrown house.

**Pull request merged**
