### PR TITLE
Bunch of changes to bee crafting station.

### PR DESCRIPTION
**Pull request by Tamamo89**
It's should be fix now hopefuly, let me know if there are any problems.
That took much longer then I thought it would.

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
there are a lot of change here, and it has conflicts with our main branch so i cannot currently merge it in.

however, we will review the contents anyhow before merging any of this in.

i do like the unlock adds. I don't like some of the other changes, but meh. 

thanks for the effort, and we'll likely get some of this included :)

**Comment by Tamamo89** [comment]
Your welcome. Figured you would like the unlock adds. Being able to craft everything from start makes it way to easy. This mod is all about hunting bees and crossbreeding them.

The majority of the frames (with the exception of the basic and miner ones) now require you to go find a frame.

Oh, and I was think perhaps the Industrial Centrifuge and Honey Jarrer should actually require Titanium bars. They are exceptionally good. The reason I put in the golden glass was to give the little hint that arid unlocks miner when crossbred with adaptive.

Speaking of which, I don't think I added unlocks for the miner or amite frames. I'll get write on that.

**Comment by NotMrFlibble** [comment]
tungstenbar.item.patch contains an error: there's a missing comma after the second instance of "isn_powersensor" (which surely shouldn't be there). You also have honeytable listed twice in the blueprints list in beestation.object.

However, these two files are the ones showing conflicts and require some editing anyway.

**Comment by Tamamo89** [comment]
Actually it looks like those are on the master branch as well.

**Comment by NotMrFlibble** [comment]
I'm thinking that those last four commits should be squashed (turned into one). You do know about _amending_ commits…?

**Comment by Tamamo89** [comment]
Fixed...

**Comment by NotMrFlibble** [comment]
Going to have to reject as it stands due to two new unlocking problems.

You need miner bees and either the uranium frame or the plutonium frame to be able to get radioactive bees, and you need radioactive bees to get plutonium bees; they don't occur in-game unless bred. However, the changes in this series mean that you need to catch a radioactive queen to unlock the uranium frame and a plutonium queen to unlock the plutonium frame.

These need to be unlocked on collection of a _miner_ queen (and you have an error in its unlocks – `titanium` rather than `titaniumframe`).

**Comment by Tamamo89** [comment]
Actually the uranium rod and uranium queen unlock the frame.
Thought I did the same for the plutonium frame, but I didn't I'll go fix it.

I'll fix the other thing too.

**Comment by NotMrFlibble** [comment]
I did a quick test with this branch checked out. Here are some highlights extracted from the log:

```[Error] Exception caught loading asset: /items/generic/crafting/tungstenbar.item, (AssetException) Could not read JSON asset /items/generic/crafting/tungstenbar.item
Caused by: (JsonParsingException) Cannot parse json file: /items/generic/crafting/tungstenbar.item
Caused by: (JsonParsingException) Error parsing json: bad array, should be ',' or ']' at 20:5
[Error] Exception caught loading asset: /items/generic/crafting/goldbar.item, (AssetException) Could not read JSON asset /items/generic/crafting/goldbar.item
Caused by: (JsonParsingException) Cannot parse json file: /items/generic/crafting/goldbar.item
Caused by: (JsonParsingException) Error parsing json: bad array, should be ',' or ']' at 9:2
[Error] Exception caught loading asset: /items/generic/crafting/refinedferozium.item, (AssetException) Could not read JSON asset /items/generic/crafting/refinedferozium.item
Caused by: (JsonParsingException) Cannot parse json file: /items/generic/crafting/refinedferozium.item
Caused by: (JsonParsingException) Error parsing json: unexpected character parsing word at 14:3
[Error] Exception caught loading asset: /items/generic/crafting/uraniumrod.item, (AssetException) Could not read JSON asset /items/generic/crafting/uraniumrod.item
Caused by: (JsonParsingException) Cannot parse json file: /items/generic/crafting/uraniumrod.item
Caused by: (JsonParsingException) Error parsing json: unexpected character parsing word at 8:1
[Error] Exception caught loading asset: /items/bees/bees/plutonium/plutoniumqueen.item, (AssetException) Could not read JSON asset /items/bees/bees/plutonium/plutoniumqueen.item
Caused by: (JsonParsingException) Cannot parse json file: /items/bees/bees/plutonium/plutoniumqueen.item
Caused by: (JsonParsingException) Error parsing json: bad object, should be ':' at 9:31
[Info] Root: Loaded ParticleDatabase in 0.0533603 seconds
[Error] Exception caught loading asset: /tiles/materials/honey/goldenplanks/goldenplank.matitem, (AssetException) Could not read JSON asset /tiles/materials/honey/goldenplanks/goldenplank.matitem
Caused by: (JsonParsingException) Cannot parse json file: /tiles/materials/honey/goldenplanks/goldenplank.matitem
Caused by: (JsonParsingException) Error parsing json: unexpected character parsing word at 19:5
[Error] Exception caught loading asset: /tiles/materials/honey/honeycrystalblock.matitem, (AssetException) Could not read JSON asset /tiles/materials/honey/honeycrystalblock.matitem
Caused by: (JsonParsingException) Cannot parse json file: /tiles/materials/honey/honeycrystalblock.matitem
Caused by: (JsonParsingException) Error parsing json: bad object, should be '}' or ',' at 13:3
[Error] Exception caught loading asset: /items/bees/combs/godlycomb.consumable, (AssetException) Could not read JSON asset /items/bees/combs/godlycomb.consumable
Caused by: (JsonParsingException) Cannot parse json file: /items/bees/combs/godlycomb.consumable
Caused by: (JsonParsingException) Error parsing json: bad object, should be '}' or ',' at 23:3```

**Comment by sayterdarkwynd** [comment]
test yo shit before you commit :) That's a lot of errors that appear right in the starbound.log file. Clear up all the errors and logic/progression issues and it's golden.

Fibble is right about the unlock btw, it should be on miners. Otherwise you break progression. I've been doing this mod for 3 years. Trust me.

**Comment by sayterdarkwynd** [comment]
didnt need to close it, just fix up the issues.

**Comment by Tamamo89** [comment]
And this is why the close and comment buttons should not be next to each other.
But yeah, I'll fix those right up.

**Comment by Tamamo89** [comment]
Had to to do a hard reset... Ugh...

**Pull request closed without merging**
