### PR TITLE
Bunnine Race addition

### PR DESCRIPTION
**Pull request by AkariEnderwolf**
I tried to do what I needed to to get the bunnine race added. Bunnine race not on workshop yet since I was trying to test compatability before uploading to workshop, and get a few more things ready for it.

### CODE REVIEW

**Comment by AkariEnderwolf** [comment]
the internal name should be "bunnine"

**Comment by sayterdarkwynd** [comment]
These are extremely OP.

**Comment by AkariEnderwolf** [comment]
so, everything is working now and is hopefully properly balanced.

**Comment by AkariEnderwolf** [comment]
what does the mastery system actually do?
Also, why have a point cost for biome immunity if it's not allowed? genuine question.

As for liquid nitrogen, couldn't find a thing for just the normal, attack inflicted, freeze status effect. The race normally lives on cold planets in lore, so they would resist or be immune to being frozen by enemy attacks.

**Comment by AkariEnderwolf** [comment]
was trying to help with the metadata includes thing, and couldn't figure out how to undo a commit when it said there were conflicts

**Comment by AkariEnderwolf** [comment]
apparently the conflict was the file ended with } when it should end with } ... no idea how that's a conflict.

**Pull request merged**
