### PR TITLE
Yet more Precursor fixes

### PR DESCRIPTION
**Pull request by Argenttip**

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
Did you lint your code first this time? I don't want to need to correct it for you again. No big deal either way, just please verify its all good.

**Comment by Argenttip** [comment]
Can you hold off on placing it until I fully finish and lint all the Precursor items?

**Comment by sayterdarkwynd** [comment]
yep. That was my intention.

**Comment by sayterdarkwynd** [comment]
is this done?

**Pull request closed without merging**
