### PR TITLE
FU armor text fixes

### PR DESCRIPTION
**Pull request by Misunderstood-Wookiee**
Fixes most of the overlapping text issues when crafting FU armors.

### CODE REVIEW

**Comment by NotMrFlibble** [comment]
Cherry-picking 304766c.seems like a good idea here.

**Comment by renbear67** [comment]
Isn't this sort of thing exactly what squash-and-merge is for? That reduces everything down to one commit.

**Comment by sayterdarkwynd** [comment]
yea, lets do that. Less worry that way. Can you do that up, wook?

**Comment by Misunderstood-Wookiee** [comment]
I would squash and merge if I knew how, I only joined Git too help with this mod Renbear was helping me half of yesterday just to understand the basics.

**Comment by renbear67** [comment]
Squash-and-merge is what we do when we click the big green button below. :-) I'll get clearance from @sayterdarkwynd tomorrow.

**Comment by Misunderstood-Wookiee** [comment]
Oh must only be visible in repo that's mine.

**Comment by Misunderstood-Wookiee** [comment]
@NotMrFlibble 
Cherry pick bad idea unless you have changed the file between this pull you need every edit in it or the status won't fit properly.  Sayter also knows he needs to unify the armors to use armornew2 at some point or we can't fix placement for all the armors as some use the vanilla tooltip.

**Pull request merged**
