### PR TITLE
Apiary code refactoring and adjustments and new feature

### PR DESCRIPTION
**Pull request by NotMrFlibble**
Code refactored into one common file and three setup files. Some (but not all) of the scented and large apiaries' settings now match those of the normal apiary. Some frames have had their behaviour adjusted to better match their descriptions.

The new feature comes into play when you have two ore-comb-generator frames in one large apiary: you get ore combs of each type. This may require some balancing (then again, ore comb spawning probably does anyway).

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
branch has conflicts that must be resolved. I won't be merging anything, period, until these conflicts are corrected.

also, you should probably look into the balance implications of these changes (the dual comb stuff) before   making such changes. 

That said, refactoring/moving things around is a good idea. They are all over the place now simply becuase when i first added bees! into FU this was where they were placed (yes, really....) and this avoided conflicts. Now that bees!~ is essentially dead, fuck it, lets make things more logical. You should probably ask first next time rather than attempt to force FU to adapt to *your* changes though, please :) No biggy though. 


So yea, address the conflicts and we're good to go. 

Oh, another thing: run Bees! changes by renbear in the future. Bees! content is officially his wheelhouse since he's been gradually replacing content in it as we go (the lua was a fucking HORRIBLE mess, but is getting better thanks to his work lol)

**Comment by sayterdarkwynd** [comment]
but yea, the changes look good.

we also need to make a check in there to either check the tag values in a farmable object for "flower" rather than manually add each flower into the script. Because that's fucking stupid and I don't know why the original author did that.

**Comment by NotMrFlibble** [comment]
Okay, I think that's everything which is *needed*, plus a little extra for consistency with @renbear67‍'s changes. If anything more needs to be changed regarding this…

**Comment by sayterdarkwynd** [comment]
sweet. i'll let renbear get everything workign in tandem as he was planning some shit prior to this being added in in the first place. Then we'll get it all intertwined and working. Thanks dude.

**Comment by renbear67** [comment]
I need to get the perfect-block bonus reset stuff working in FR, then I'll work on merging this in. Hopefully within a couple days.

**Pull request merged**
