### PR TITLE
Fixes to #1865 (Mech fuel pickup) and #1866 (Operative Cap mask)

### PR DESCRIPTION
**Pull request by lamialily**
The silent issue closure did not give me any comfort in the issue being addressed so I took this matter if nothing else into my own hands. I will look into patching #1865 later.

Tested my changes to the build and it looks pretty solid, if I do say so myself. Have an example in full Operative gear, with hair and everything.
Screenshot_2019-06-29_17-18-49

If this is unnecessarily stepping on toes, I apologize, but there was no README or CONTRIBUTING file in the repository and so far responsiveness has been null, so I had to work on the bare minimum  of the repository being public and PRs being accepted in the past.

### CODE REVIEW

**Comment by lamialily** [comment]
Looks like it added the commit for the other one automatically after pushing. No skin off my back.

**Comment by sayterdarkwynd** [comment]
I made both of the changes , which is why the issues were closed.

**Comment by lamialily** [comment]
Well, so long as they're fixed, I suppose.

**Comment by lamialily** [comment]
On that note, do you discuss development elsewhere so that I may be able to avoid making redundant fixes in the future?

**Pull request closed without merging**
