### PR TITLE
Added the Mech Platform to the mech research branch

### PR DESCRIPTION
**Pull request by Zarra-0**
The mech platform was added by CF in the same way that most objects were - through the pixel printer, scanned in the world. Unlocking it through the research system will incentivise players to use their mechs more, and thus continue with the mech research branch, as well as making mechs easier to use and less distinct from the rest of the game.

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
i have absolutely no interest in letting players summon mechs any time prior to completing the bounty system. Its cheap, breaks every single boss fight, etc.

**Comment by sayterdarkwynd** [comment]
also..conflicts here.

**Comment by Zarra-0** [comment]
The only boss fight I can think of that has enough non-protected terrain to place down the spawner is Shog, which is late-game enough that players could have completed the bounty system at that stage anyways. I'm not too fussed over it, though. Just wish I had the option to bring in my mech halfway through exploring a world.

I don't understand the conflict report. It looks like the regular "add a word" change that's merged just fine in the past.

**Comment by sayterdarkwynd** [comment]
well, ill give it some thought. Not hyped about the idea, but if its just the vanilla object I'm not overly concerned.

**Comment by Kherae** [comment]
if we do add it, we need to make shoggoth one-shot mechs with an eyebeam laser

**Comment by sayterdarkwynd** [comment]
added in, manually

**Pull request closed without merging**
