### PR TITLE
Collection script fix

### PR DESCRIPTION
**Pull request by ColonolNutty**
There was a slight coding error that would cause the collections window to blow up if you had a custom collection selected when you closed it and reopened it again.

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
https://images-ext-1.discordapp.net/external/bsbXNV1DOAwGqek_1U1C8kPi8znI4AAR1f6dd8Rujyo/https/image.prntscr.com/image/1-vJc1bMRA6aytkYYw6LJg.png

**Comment by ColonolNutty** [comment]
... That isn't what I see locally...

**Comment by sayterdarkwynd** [comment]
im aware. so as stated, it isnt playing nicely with *something*

**Comment by ColonolNutty** [comment]
I've only got Frackin Universe and More Framing installed

**Comment by sayterdarkwynd** [comment]
Still suspect Elithian Races. I had issues with collections doing it the first time because of that mod too

**Comment by ColonolNutty** [comment]
Perhaps Frackin isn't ready for this change just yet then :/

**Comment by sayterdarkwynd** [comment]
for the time being, im reverting the files to their original. 

on that note, you are 100% free to integrate the FU method of collections, verbatim, if needed, on your end.

**Comment by ColonolNutty** [comment]
It won't matter, because you have MFM in your "includes" thus overwriting all changes made in it

**Comment by sayterdarkwynd** [comment]
ah. i dont think i need that include now though.

**Comment by sayterdarkwynd** [comment]
ill try pulling it. let me know what happens.

**Comment by ColonolNutty** [comment]
You can easily revert this by hitting revert here, instead of manually making the commit

**Comment by sayterdarkwynd** [comment]
i would, but every time i try fucks up. 10/10 times so far.

**Comment by ColonolNutty** [comment]
I do it often at my work and I have yet to have it mess up. It truly messes up when there are commits that modify the same files that won't be reverted.

**Comment by sayterdarkwynd** [comment]
im not even sure why YesChef and MoreFarming *have* includes in FU.

**Comment by ColonolNutty** [comment]
No idea, but it would help immensely if they were removed. I was planning on adding FU and MFM support in the respective More Farming: Fracking Universe Addon

**Comment by sayterdarkwynd** [comment]
in any case, ive pushed my removal to the branch. give it a pull and see if everything works on your end.

**Comment by ColonolNutty** [comment]
Wait, this branch should be reverted. This fixes a script error.

**Comment by ColonolNutty** [comment]
This needs to be put back in, the lua changes have been verified

**Pull request merged**
